Install React Hook Form, RTK, add reducer with store in project, add …
MaxLisyanskiy/strada-pet pull request #26
Opened 2023-12-17 19:10 UTC by AipovAlexander

…dark theme

**1. Task name**  
Install Ant Design #10
Install RTK #13

**2. Issue link**  
[link](https://github.com/MaxLisyanskiy/strada-pet/issues/10)
[link](https://github.com/MaxLisyanskiy/strada-pet/issues/13)

**3. Tasks**

- [x] Install RTK 
- [x] Add reducer and store
- [x] Add dark theme
- [x] Add switcher dark/light
- [x] Install React Hook Form

2023-12-17 19:12 UTC, freddypopa commented on src/App.tsx
> +  const getThemeFromStore = useSelector((state) => state.posts.userTheme);
для таких моментом предлагаю отдельный файл selectors и будем из него импортить (state) => state.posts.userTheme такие вещи

2023-12-17 19:40 UTC, MaxLisyanskiy requested changes
Хорошая работа, но есть пару недочетов. Просьба исправить)

2023-12-17 19:40 UTC, MaxLisyanskiy commented on src/pages/profile.tsx
> +      <Input placeholder="Введите текст"></Input>
Зачем закрывающий тег? Можно сделать одним

2023-12-17 19:40 UTC, MaxLisyanskiy commented on src/redux/reducer.ts
> +export default reducer.reducer;
1) Необходимо создать отдельную папку reducers в папке store, где будут храниться все reducers
2) Переименовать reducer по смыслу - themeSlice (название файла, название слайса)
3) Изменить name

2023-12-17 19:40 UTC, MaxLisyanskiy commented on src/redux/store.ts
> +export default store;
1) Добавить типы для store (RootState, AppStore, AppDispatch)
2) На основе этих типов создать два типизированных кастомных хука `useAppDispatch` и `useAppSelector`, чтобы в дальнейшем не приходилось типизировать обычные selector и dispatch

3) Изменить название у posts reducer - у тебя он отвечает за переключение темы!
Например, themeReducer

2023-12-17 19:40 UTC, MaxLisyanskiy commented on src/App.tsx
> +  const getThemeFromStore = useSelector((state) => state.posts.userTheme);
Саша, как создашь типизированный `useAppSelector`, необходимо здесь его использовать

2023-12-17 19:40 UTC, MaxLisyanskiy commented on src/App.tsx
> +    >
Почему бы не использовать такую конструкцию `const { userTheme } = useAppSelector((state) => state.post)` ?  (не забудь что у тебя редьюсер post измениться)

А затем сразу передать это в компонент с тернарником  
` theme={{
 algorithm: !userTheme ? '' : theme.darkAlgorithm
}} `

2023-12-17 19:40 UTC, MaxLisyanskiy commented on src/pages/profile.tsx
> +  const userTheme = useSelector((state) => state.posts.userTheme);
Можно сразу вытянуть `const { userTheme} = useAppSelector((state) => state.themeReducer);`

2023-12-18 04:33 UTC, AipovAlexander commented on src/pages/profile.tsx
> +      <Input placeholder="Введите текст"></Input>
Привык так делать, исправлю, спасибо

2023-12-18 13:02 UTC, merged